// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SitemaProjeto.Data;

#nullable disable

namespace SitemaProjeto.Migrations
{
    [DbContext(typeof(SistemaProjetoContext))]
    [Migration("20230510171152_FirstStep")]
    partial class FirstStep
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlunoGrupo", b =>
                {
                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.HasKey("IdAluno", "IdGrupo");

                    b.ToTable("AlunoGrupo");
                });

            modelBuilder.Entity("Pertence", b =>
                {
                    b.Property<int>("IdAluno")
                        .HasColumnType("int")
                        .HasColumnName("ID_Aluno");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int")
                        .HasColumnName("ID_Grupo");

                    b.HasKey("IdAluno", "IdGrupo")
                        .HasName("PK__Pertence__FE5331A80B303854");

                    b.HasIndex("IdGrupo");

                    b.ToTable("Pertence", (string)null);
                });

            modelBuilder.Entity("SitemaProjeto.Models.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Aluno");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAluno"));

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NumeroMec")
                        .HasColumnType("int")
                        .HasColumnName("Numero_Mec");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdAluno")
                        .HasName("PK__Aluno__06D5E4761F943BAA");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Candidatura", b =>
                {
                    b.Property<int>("IdGrupo")
                        .HasColumnType("int")
                        .HasColumnName("ID_Grupo");

                    b.Property<int>("IdProjeto")
                        .HasColumnType("int")
                        .HasColumnName("ID_projeto");

                    b.Property<int>("OrdemPreferencia")
                        .HasColumnType("int")
                        .HasColumnName("Ordem_Preferencia");

                    b.Property<bool?>("Resultado")
                        .HasColumnType("bit");

                    b.Property<int>("Seriacao")
                        .HasColumnType("int");

                    b.HasKey("IdGrupo", "IdProjeto")
                        .HasName("PK__Candidat__994EB61DBEB601F1");

                    b.HasIndex("IdProjeto");

                    b.ToTable("Candidatura");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Edicao", b =>
                {
                    b.Property<int>("IdEdicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Edicao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEdicao"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ValidoAte")
                        .HasColumnType("int")
                        .HasColumnName("Valido_ate");

                    b.Property<int>("ValidoDe")
                        .HasColumnType("int")
                        .HasColumnName("Valido_de");

                    b.HasKey("IdEdicao")
                        .HasName("PK__Edicao__FB4794052FD7C2F0");

                    b.ToTable("Edicao");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Externo", b =>
                {
                    b.Property<int>("IdExterno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Externo");

                    b.HasKey("IdExterno")
                        .HasName("PK__Externo__CF4B12E03BA2BD65");

                    b.ToTable("Externo");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Grupo", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Grupo");

                    b.Property<int>("IdEdicao")
                        .HasColumnType("int")
                        .HasColumnName("ID_Edicao");

                    b.HasKey("IdGrupo")
                        .HasName("PK__Grupo__886D5DEECDF1CD75");

                    b.HasIndex("IdEdicao");

                    b.ToTable("Grupo");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Interno", b =>
                {
                    b.Property<int>("IdInterno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Interno");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdInterno")
                        .HasName("PK__Interno__EEA2B8265207726E");

                    b.ToTable("Interno");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Orientador", b =>
                {
                    b.Property<int>("IdOrientador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Orientador");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrientador"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdOrientador")
                        .HasName("PK__Orientad__C15B3CC7AA06E5C6");

                    b.ToTable("Orientador");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Orientum", b =>
                {
                    b.Property<int>("IdOrientador")
                        .HasColumnType("int")
                        .HasColumnName("ID_Orientador");

                    b.Property<int>("IdProjeto")
                        .HasColumnType("int")
                        .HasColumnName("ID_Projeto");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdOrientador", "IdProjeto")
                        .HasName("PK__Orienta__EC6A0D1CBD0E5614");

                    b.HasIndex("IdProjeto");

                    b.ToTable("Orienta");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Projeto", b =>
                {
                    b.Property<int>("IdProjeto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Projeto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProjeto"));

                    b.Property<string>("Apresentacao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("AreaInvestigacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Area_Investigacao");

                    b.Property<string>("CentroInvestigacao")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Centro_Investigacao");

                    b.Property<int>("IdEdicao")
                        .HasColumnType("int")
                        .HasColumnName("ID_Edicao");

                    b.Property<int>("IdOrientador")
                        .HasColumnType("int")
                        .HasColumnName("ID_Orientador");

                    b.Property<int>("NumAlunos")
                        .HasColumnType("int")
                        .HasColumnName("Num_Alunos");

                    b.Property<string>("Objetivos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdProjeto")
                        .HasName("PK__Projeto__D3131DB335E3DA52");

                    b.HasIndex("IdEdicao");

                    b.HasIndex("IdOrientador");

                    b.ToTable("Projeto");
                });

            modelBuilder.Entity("Pertence", b =>
                {
                    b.HasOne("SitemaProjeto.Models.Aluno", null)
                        .WithMany()
                        .HasForeignKey("IdAluno")
                        .IsRequired()
                        .HasConstraintName("FK__Pertence__ID_Alu__3F466844");

                    b.HasOne("SitemaProjeto.Models.Grupo", null)
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .IsRequired()
                        .HasConstraintName("FK__Pertence__ID_Gru__403A8C7D");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Candidatura", b =>
                {
                    b.HasOne("SitemaProjeto.Models.Grupo", "IdGrupoNavigation")
                        .WithMany("Candidaturas")
                        .HasForeignKey("IdGrupo")
                        .IsRequired()
                        .HasConstraintName("FK__Candidatu__ID_Gr__37A5467C");

                    b.HasOne("SitemaProjeto.Models.Projeto", "IdProjetoNavigation")
                        .WithMany("Candidaturas")
                        .HasForeignKey("IdProjeto")
                        .IsRequired()
                        .HasConstraintName("FK__Candidatu__ID_pr__38996AB5");

                    b.Navigation("IdGrupoNavigation");

                    b.Navigation("IdProjetoNavigation");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Externo", b =>
                {
                    b.HasOne("SitemaProjeto.Models.Orientador", "IdExternoNavigation")
                        .WithOne("Externo")
                        .HasForeignKey("SitemaProjeto.Models.Externo", "IdExterno")
                        .IsRequired()
                        .HasConstraintName("FK__Externo__ID_Exte__267ABA7A");

                    b.Navigation("IdExternoNavigation");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Grupo", b =>
                {
                    b.HasOne("SitemaProjeto.Models.Edicao", "IdEdicaoNavigation")
                        .WithMany("Grupos")
                        .HasForeignKey("IdEdicao")
                        .IsRequired()
                        .HasConstraintName("FK__Grupo__ID_Edicao__33D4B598");

                    b.HasOne("SitemaProjeto.Models.Aluno", "IdGrupoNavigation")
                        .WithOne("Grupo")
                        .HasForeignKey("SitemaProjeto.Models.Grupo", "IdGrupo")
                        .IsRequired()
                        .HasConstraintName("FK__Grupo__ID_Grupo__34C8D9D1");

                    b.Navigation("IdEdicaoNavigation");

                    b.Navigation("IdGrupoNavigation");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Interno", b =>
                {
                    b.HasOne("SitemaProjeto.Models.Orientador", "IdInternoNavigation")
                        .WithOne("Interno")
                        .HasForeignKey("SitemaProjeto.Models.Interno", "IdInterno")
                        .IsRequired()
                        .HasConstraintName("FK__Interno__ID_Inte__29572725");

                    b.Navigation("IdInternoNavigation");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Orientum", b =>
                {
                    b.HasOne("SitemaProjeto.Models.Orientador", "IdOrientadorNavigation")
                        .WithMany("Orienta")
                        .HasForeignKey("IdOrientador")
                        .IsRequired()
                        .HasConstraintName("FK__Orienta__ID_Orie__3B75D760");

                    b.HasOne("SitemaProjeto.Models.Projeto", "IdProjetoNavigation")
                        .WithMany("Orienta")
                        .HasForeignKey("IdProjeto")
                        .IsRequired()
                        .HasConstraintName("FK__Orienta__ID_Proj__3C69FB99");

                    b.Navigation("IdOrientadorNavigation");

                    b.Navigation("IdProjetoNavigation");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Projeto", b =>
                {
                    b.HasOne("SitemaProjeto.Models.Edicao", "IdEdicaoNavigation")
                        .WithMany("Projetos")
                        .HasForeignKey("IdEdicao")
                        .IsRequired()
                        .HasConstraintName("FK__Projeto__ID_Edic__300424B4");

                    b.HasOne("SitemaProjeto.Models.Orientador", "IdOrientadorNavigation")
                        .WithMany("Projetos")
                        .HasForeignKey("IdOrientador")
                        .IsRequired()
                        .HasConstraintName("FK__Projeto__ID_Orie__30F848ED");

                    b.Navigation("IdEdicaoNavigation");

                    b.Navigation("IdOrientadorNavigation");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Aluno", b =>
                {
                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Edicao", b =>
                {
                    b.Navigation("Grupos");

                    b.Navigation("Projetos");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Grupo", b =>
                {
                    b.Navigation("Candidaturas");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Orientador", b =>
                {
                    b.Navigation("Externo");

                    b.Navigation("Interno");

                    b.Navigation("Orienta");

                    b.Navigation("Projetos");
                });

            modelBuilder.Entity("SitemaProjeto.Models.Projeto", b =>
                {
                    b.Navigation("Candidaturas");

                    b.Navigation("Orienta");
                });
#pragma warning restore 612, 618
        }
    }
}
